### ISSUE TITLE
Use Case Descriptions

### ISSUE THREAD

**Issue by ImmanuelLoh** [Sacred29/INF2001-Team-Project#2]

**Comment by Sacred29** [comment]
### Description
Develop comprehensive use case descriptions for each major feature of the project. These use cases should describe how different types of users interact with the system, outlining the steps, scenarios, and outcomes for each action. The use cases will serve as a foundation for development, testing, and client validation.

### Task Breakdown

1. Identify the key features of the system that require use case descriptions.
2. Define user Actor(s) involved in each use case.
3. Draft detailed use case descriptions for each feature, including:
- Primary actor 
- Preconditions
- Main success scenario
- Alternate scenarios
- Postconditions
Note: Do not include externalities(?)
4. Review and validate the use cases with the project team to ensure completeness.
5. Submit use cases to stakeholders for approval.
6. Update any existing project documentation to reflect the use cases.

### Acceptance Criteria
1. Use cases are written for all major features, covering both the main success path and alternate scenarios.
2. Use cases are reviewed and approved by the internal project team.
3. Stakeholders have reviewed the use cases and provided feedback or approval.
4. The use case descriptions are integrated into the project's documentation.

**Comment by Sacred29** [comment]
# Review of Use Case Descriptions
## Use Case Description Sample
![Image](https://github.com/user-attachments/assets/b48f7cd0-95ed-4206-8ade-21f30939b370)
![Image](https://github.com/user-attachments/assets/360c24ba-a530-41bf-afab-bf754a8bc7ce)
![Image](https://github.com/user-attachments/assets/b14f7a5e-ffb8-4adf-9632-d36882327617)
![Image](https://github.com/user-attachments/assets/e2771098-41ab-4cdc-b5da-d337f565dc93)

## Use Case Description Feedback
![Image](https://github.com/user-attachments/assets/ce1fedca-7ea0-4730-83e1-0159353d0942)

**Comment by Sacred29** [comment]
# Deliverables
Complete Use case Descriptions for M1 Report.
![Image](https://github.com/user-attachments/assets/e5c4cdc8-f1e3-40df-bb20-1255569f4cc8)
